-- MySQL Script generated by MySQL Workbench
-- 05/07/17 02:54:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ctam
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ctam` ;

-- -----------------------------------------------------
-- Schema ctam
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ctam` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema control
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `control` ;

-- -----------------------------------------------------
-- Schema control
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `control` ;
USE `ctam` ;

-- -----------------------------------------------------
-- Table `ctam`.`experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`experiment` ;

CREATE TABLE IF NOT EXISTS `ctam`.`experiment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `submitter` VARCHAR(255) NULL,
  `affiliation` VARCHAR(45) NULL,
  `date` DATE NULL,
  `description` BLOB NULL,
  `processed` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`cell_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`cell_line` ;

CREATE TABLE IF NOT EXISTS `ctam`.`cell_line` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `species` VARCHAR(45) NOT NULL,
  `source` VARCHAR(255) NULL,
  `growth` VARCHAR(25) NULL,
  `morphology` VARCHAR(45) NULL,
  `disease` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`protein`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`protein` ;

CREATE TABLE IF NOT EXISTS `ctam`.`protein` (
  `id` VARCHAR(45) NOT NULL,
  `accession` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `gene` VARCHAR(100) NULL,
  `gene_id` VARCHAR(45) NULL COMMENT 'thie column will be appended to the link \"http://www.genenames.org/cgi-bin/gene_symbol_report?hgnc_id=\" to provide the link for the gene',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`regulator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`regulator` ;

CREATE TABLE IF NOT EXISTS `ctam`.`regulator` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `CAS` VARCHAR(45) NULL,
  `formula` VARCHAR(80) NULL,
  `mw` FLOAT NULL,
  `main_target` VARCHAR(45) CHARACTER SET 'utf8' NULL,
  `activity_link` INT NULL COMMENT 'combine with http://www.kinase-screen.mrc.ac.uk/screening-compounds/ to provide the activity data',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'superclass for kinase inhibitors, agonists';


-- -----------------------------------------------------
-- Table `ctam`.`kinase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`kinase` ;

CREATE TABLE IF NOT EXISTS `ctam`.`kinase` (
  `display` VARCHAR(45) NOT NULL,
  `protein_id` VARCHAR(45) NOT NULL,
  `group` VARCHAR(45) NULL,
  PRIMARY KEY (`display`),
  INDEX `kinase_protein_id_idx` (`protein_id` ASC),
  CONSTRAINT `kinase_protein_id`
    FOREIGN KEY (`protein_id`)
    REFERENCES `ctam`.`protein` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`regulation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`regulation` ;

CREATE TABLE IF NOT EXISTS `ctam`.`regulation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `regulator_id` INT NOT NULL,
  `kinase_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `kinase_inhibitor_kinase_idx` (`kinase_name` ASC),
  CONSTRAINT `regulator_regulation`
    FOREIGN KEY (`regulator_id`)
    REFERENCES `ctam`.`regulator` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `kinase_regulation`
    FOREIGN KEY (`kinase_name`)
    REFERENCES `ctam`.`kinase` (`protein_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`run`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`run` ;

CREATE TABLE IF NOT EXISTS `ctam`.`run` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `spectral_file_name` VARCHAR(255) NULL,
  `spectral_file_format` VARCHAR(5) NULL,
  `spectral_file_location` VARCHAR(255) NULL,
  `spectral_repository_name` VARCHAR(45) NULL,
  `spectral_repository_accession` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`runs_in_experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`runs_in_experiment` ;

CREATE TABLE IF NOT EXISTS `ctam`.`runs_in_experiment` (
  `run_id` INT NOT NULL,
  `experiment_id` INT NOT NULL,
  `group` VARCHAR(45) NOT NULL COMMENT 'role column describes the purpose/role of the run in the experiment, e.g. control, 24h treatment',
  PRIMARY KEY (`run_id`, `experiment_id`, `group`),
  INDEX `experiment_runs_in_experiment_idx` (`experiment_id` ASC),
  INDEX `experiment_group_runs_in_experiment_idx` (`group` ASC, `experiment_id` ASC),
  CONSTRAINT `run_runs_in_experiment`
    FOREIGN KEY (`run_id`)
    REFERENCES `ctam`.`run` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `experiment_runs_in_experiment`
    FOREIGN KEY (`experiment_id`)
    REFERENCES `ctam`.`experiment` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`search_parameter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`search_parameter` ;

CREATE TABLE IF NOT EXISTS `ctam`.`search_parameter` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fasta_file` VARCHAR(255) NOT NULL,
  `enzyme` VARCHAR(45) NULL,
  `peptide_tolerance` FLOAT NULL,
  `peptide_tolerance_unit` VARCHAR(45) NULL,
  `product_tolerance` FLOAT NULL,
  `product_tolerance_unit` VARCHAR(45) NULL,
  `miscleavage` INT(1) NULL,
  `min_charge` INT(1) NULL,
  `max_charge` INT(1) NULL,
  `species` VARCHAR(45) NULL,
  `species_taxo_id` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`modification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`modification` ;

CREATE TABLE IF NOT EXISTS `ctam`.`modification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `mw_shift` FLOAT NULL,
  `site` VARCHAR(20) NULL,
  `display` VARCHAR(60) NULL,
  `PSIMOD_accession` VARCHAR(45) NULL,
  `UNIMOD_accession` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`search_parameter_modification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`search_parameter_modification` ;

CREATE TABLE IF NOT EXISTS `ctam`.`search_parameter_modification` (
  `search_parameter_id` INT NOT NULL,
  `modification_id` INT NOT NULL,
  `is_fixed` TINYINT(1) NULL,
  PRIMARY KEY (`search_parameter_id`, `modification_id`),
  INDEX `modification_psm_modification_idx` (`modification_id` ASC),
  CONSTRAINT `search_parameter_search_parameter_modification`
    FOREIGN KEY (`search_parameter_id`)
    REFERENCES `ctam`.`search_parameter` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `modification_search_parameter_modification`
    FOREIGN KEY (`modification_id`)
    REFERENCES `ctam`.`modification` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`identification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`identification` ;

CREATE TABLE IF NOT EXISTS `ctam`.`identification` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `run_id` INT NOT NULL,
  `identification_file` VARCHAR(255) NOT NULL,
  `search_parameter_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `run_identification_idx` (`run_id` ASC),
  INDEX `search_parameter_identification_idx` (`search_parameter_id` ASC),
  CONSTRAINT `run_identification`
    FOREIGN KEY (`run_id`)
    REFERENCES `ctam`.`run` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `search_parameter_identification`
    FOREIGN KEY (`search_parameter_id`)
    REFERENCES `ctam`.`search_parameter` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`psm`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`psm` ;

CREATE TABLE IF NOT EXISTS `ctam`.`psm` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `identification_id` INT NOT NULL,
  `spectrum_title` VARCHAR(255) NULL,
  `peptide` VARCHAR(100) NOT NULL,
  `protein_id` VARCHAR(45) NULL,
  `start` INT NULL,
  `end` INT NULL,
  `protein_score` FLOAT NULL,
  `rank` INT NOT NULL,
  `rt` FLOAT NULL,
  `charge` INT NULL,
  `observed_mz` DOUBLE NULL,
  `ion_intensity` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `identification_psm_idx` (`identification_id` ASC),
  INDEX `protein_psm_idx` (`protein_id` ASC),
  INDEX `peptide_psm_idx` (`peptide` ASC),
  INDEX `rank_psm_idx` (`rank` ASC),
  INDEX `charge_psm_idx` (`charge` ASC),
  INDEX `rt_psm_idx` (`rt` ASC),
  CONSTRAINT `identification_psm`
    FOREIGN KEY (`identification_id`)
    REFERENCES `ctam`.`identification` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `protein_psm`
    FOREIGN KEY (`protein_id`)
    REFERENCES `ctam`.`protein` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`psm_modification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`psm_modification` ;

CREATE TABLE IF NOT EXISTS `ctam`.`psm_modification` (
  `psm_id` INT NOT NULL,
  `modification_id` INT NOT NULL,
  `location` INT NOT NULL,
  `affected_aa` VARCHAR(1) NOT NULL,
  `confidence_score` FLOAT NULL,
  `confidence_cv_term` VARCHAR(45) NULL,
  PRIMARY KEY (`psm_id`, `modification_id`, `location`),
  INDEX `modification_psm_modification_idx` (`modification_id` ASC),
  CONSTRAINT `psm_psm_modification`
    FOREIGN KEY (`psm_id`)
    REFERENCES `ctam`.`psm` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `modification_psm_modification`
    FOREIGN KEY (`modification_id`)
    REFERENCES `ctam`.`modification` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`regulator_network`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`regulator_network` ;

CREATE TABLE IF NOT EXISTS `ctam`.`regulator_network` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cell_line_id` INT NOT NULL,
  `serial` INT NOT NULL,
  `regulator_id` INT NOT NULL,
  `precessor_regulator_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `regulator_regulator_existance_idx` (`regulator_id` ASC),
  INDEX `cell_line_regulator_existance_idx` (`cell_line_id` ASC),
  INDEX `precessor_regulator_existance_idx` (`precessor_regulator_id` ASC),
  CONSTRAINT `regulator_regulator_existance`
    FOREIGN KEY (`regulator_id`)
    REFERENCES `ctam`.`regulator` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `precessor_regulator_existance`
    FOREIGN KEY (`precessor_regulator_id`)
    REFERENCES `ctam`.`regulator` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cell_line_regulator_existance`
    FOREIGN KEY (`cell_line_id`)
    REFERENCES `ctam`.`cell_line` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`regulation_observation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`regulation_observation` ;

CREATE TABLE IF NOT EXISTS `ctam`.`regulation_observation` (
  `experiment_id` INT NOT NULL,
  `regulation_id` INT NOT NULL,
  PRIMARY KEY (`experiment_id`, `regulation_id`),
  CONSTRAINT `regulation_regulation_observation`
    FOREIGN KEY (`regulation_id`)
    REFERENCES `ctam`.`regulation` (`regulator_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`peptide`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`peptide` ;

CREATE TABLE IF NOT EXISTS `ctam`.`peptide` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sequence` VARCHAR(100) NULL,
  `protein` VARCHAR(45) NULL,
  `start` INT NULL,
  `end` INT NULL,
  `charge` INT(1) NULL,
  `mz` DOUBLE NULL,
  `modification_str` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `protein_peptide_idx` (`protein` ASC),
  CONSTRAINT `protein_peptide`
    FOREIGN KEY (`protein`)
    REFERENCES `ctam`.`protein` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`vendor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`vendor` ;

CREATE TABLE IF NOT EXISTS `ctam`.`vendor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `website` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`cell_line_used`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`cell_line_used` ;

CREATE TABLE IF NOT EXISTS `ctam`.`cell_line_used` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cell_line_id` INT NOT NULL,
  `vendor_id` INT NOT NULL,
  `variant` VARCHAR(45) NULL,
  `description` VARCHAR(255) NULL,
  `vendor_product_id` VARCHAR(45) NULL,
  `link` VARCHAR(255) NULL COMMENT 'combining with the website field in table vendor, it gives the full link to the specific product',
  PRIMARY KEY (`id`),
  INDEX `cell_line_cell_line_used_idx` (`cell_line_id` ASC),
  INDEX `vendor_cell_line_used_idx` (`vendor_id` ASC),
  CONSTRAINT `cell_line_cell_line_used`
    FOREIGN KEY (`cell_line_id`)
    REFERENCES `ctam`.`cell_line` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `vendor_cell_line_used`
    FOREIGN KEY (`vendor_id`)
    REFERENCES `ctam`.`vendor` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`experiment_cell_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`experiment_cell_line` ;

CREATE TABLE IF NOT EXISTS `ctam`.`experiment_cell_line` (
  `experiment_id` INT NOT NULL,
  `cell_line_used_id` INT NOT NULL,
  PRIMARY KEY (`experiment_id`, `cell_line_used_id`),
  INDEX `cell_line_experiment_cell_line_idx` (`cell_line_used_id` ASC),
  CONSTRAINT `experiment_experiment_cell_line`
    FOREIGN KEY (`experiment_id`)
    REFERENCES `ctam`.`experiment` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cell_line_used_experiment_cell_line`
    FOREIGN KEY (`cell_line_used_id`)
    REFERENCES `ctam`.`cell_line_used` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'redundant table, serve as a cache of select rcl.cell_line_used_id from runs_in_experiment re, run_cell_line rcl where rcl.run_id = re.run_id and re.experiment_id = {EXPERIMENT ID}';


-- -----------------------------------------------------
-- Table `ctam`.`final_result`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`final_result` ;

CREATE TABLE IF NOT EXISTS `ctam`.`final_result` (
  `peptide_id` INT NOT NULL,
  `experiment_id` INT NOT NULL,
  `cell_line_used_id` INT NOT NULL,
  `group_id` VARCHAR(45) NOT NULL,
  `fold_change` DOUBLE NULL,
  `pvalue` DOUBLE NULL,
  `identified_times` INT NULL,
  PRIMARY KEY (`peptide_id`, `experiment_id`, `group_id`, `cell_line_used_id`),
  INDEX `experiment_final_result_idx` (`experiment_id` ASC, `cell_line_used_id` ASC),
  INDEX `treatment_final_result_idx` (`group_id` ASC, `experiment_id` ASC),
  CONSTRAINT `peptide_final_result`
    FOREIGN KEY (`peptide_id`)
    REFERENCES `ctam`.`peptide` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cell_line_experiment_final_result`
    FOREIGN KEY (`experiment_id` , `cell_line_used_id`)
    REFERENCES `ctam`.`experiment_cell_line` (`experiment_id` , `cell_line_used_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `treatment_final_result`
    FOREIGN KEY (`group_id` , `experiment_id`)
    REFERENCES `ctam`.`runs_in_experiment` (`group` , `experiment_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'In one experiment, several treatments could be applied. The value change of the same peptide under different treatments could be the indicator';


-- -----------------------------------------------------
-- Table `ctam`.`treatment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`treatment` ;

CREATE TABLE IF NOT EXISTS `ctam`.`treatment` (
  `run_id` INT NOT NULL,
  `regulator_id` INT NOT NULL,
  PRIMARY KEY (`run_id`, `regulator_id`),
  INDEX `regulator_treatment_idx` (`regulator_id` ASC),
  CONSTRAINT `run_treatment`
    FOREIGN KEY (`run_id`)
    REFERENCES `ctam`.`run` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `regulator_treatment`
    FOREIGN KEY (`regulator_id`)
    REFERENCES `ctam`.`regulator` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`psm_score`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`psm_score` ;

CREATE TABLE IF NOT EXISTS `ctam`.`psm_score` (
  `psm_id` INT NOT NULL,
  `score_name` VARCHAR(45) NOT NULL,
  `score_cv_term` VARCHAR(45) NULL,
  `score_value` FLOAT NULL,
  PRIMARY KEY (`psm_id`, `score_name`),
  CONSTRAINT `psm_psm_score`
    FOREIGN KEY (`psm_id`)
    REFERENCES `ctam`.`psm` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`experiment_regulator`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`experiment_regulator` ;

CREATE TABLE IF NOT EXISTS `ctam`.`experiment_regulator` (
  `experiment_id` INT NOT NULL,
  `regulator_id` INT NOT NULL,
  PRIMARY KEY (`experiment_id`, `regulator_id`),
  INDEX `regulator_experiment_regulator_idx` (`regulator_id` ASC),
  CONSTRAINT `experiment_experiment_regulator`
    FOREIGN KEY (`experiment_id`)
    REFERENCES `ctam`.`experiment` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `regulator_experiment_regulator`
    FOREIGN KEY (`regulator_id`)
    REFERENCES `ctam`.`regulator` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'redundant table, serve as a cache of select r.name from regulator r, runs_in_experiment re,  treatment t where r.id = t.regulator_id and t.run_id = re.run_id and re.experiment_id = {EXPERIMENT ID}';


-- -----------------------------------------------------
-- Table `ctam`.`calculated_RT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`calculated_RT` ;

CREATE TABLE IF NOT EXISTS `ctam`.`calculated_RT` (
  `experiment_id` INT NOT NULL,
  `run_id` INT NOT NULL,
  `peptide_id` INT NOT NULL,
  `value` FLOAT NOT NULL,
  PRIMARY KEY (`experiment_id`, `run_id`, `peptide_id`),
  INDEX `peptide_calculated_RT_idx` (`peptide_id` ASC),
  CONSTRAINT `experiment_and_run_calculated_RT`
    FOREIGN KEY (`experiment_id` , `run_id`)
    REFERENCES `ctam`.`runs_in_experiment` (`experiment_id` , `run_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `peptide_calculated_RT`
    FOREIGN KEY (`peptide_id`)
    REFERENCES `ctam`.`peptide` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`software`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`software` ;

CREATE TABLE IF NOT EXISTS `ctam`.`software` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `cv_accession` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`identification_software`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`identification_software` ;

CREATE TABLE IF NOT EXISTS `ctam`.`identification_software` (
  `identification_id` INT NOT NULL,
  `software_id` INT NOT NULL,
  `version` VARCHAR(45) NULL,
  `customization` BLOB NULL,
  PRIMARY KEY (`identification_id`, `software_id`),
  INDEX `software_identification_software_idx` (`software_id` ASC),
  CONSTRAINT `software_identification_software`
    FOREIGN KEY (`software_id`)
    REFERENCES `ctam`.`software` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `identification_identification_software`
    FOREIGN KEY (`identification_id`)
    REFERENCES `ctam`.`identification` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`best_psm_in_identification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`best_psm_in_identification` ;

CREATE TABLE IF NOT EXISTS `ctam`.`best_psm_in_identification` (
  `psm_id` INT NOT NULL,
  `max_score` FLOAT NULL,
  `mean_score` FLOAT NULL,
  `max_delta` FLOAT NULL,
  `min_ppm` DOUBLE NULL,
  `max_ppm` DOUBLE NULL,
  `mean_ppm` DOUBLE NULL,
  `min_rt` FLOAT NULL,
  `max_rt` FLOAT NULL,
  `max_expectancy` DOUBLE NULL,
  `mean_expectancy` DOUBLE NULL,
  `number_of_psms` INT NULL,
  `total_ion_intensity` DOUBLE NULL,
  PRIMARY KEY (`psm_id`),
  CONSTRAINT `psm_best_psm_in_run`
    FOREIGN KEY (`psm_id`)
    REFERENCES `ctam`.`psm` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`peak_area`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`peak_area` ;

CREATE TABLE IF NOT EXISTS `ctam`.`peak_area` (
  `experiment_id` INT NOT NULL,
  `run_id` INT NOT NULL,
  `peptide_id` INT NOT NULL,
  `value` DOUBLE NOT NULL,
  PRIMARY KEY (`experiment_id`, `run_id`, `peptide_id`),
  INDEX `peptide_peak_area_idx` (`peptide_id` ASC),
  CONSTRAINT `experiment_and_run_peak_area`
    FOREIGN KEY (`experiment_id` , `run_id`)
    REFERENCES `ctam`.`runs_in_experiment` (`experiment_id` , `run_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `peptide_peak_area`
    FOREIGN KEY (`peptide_id`)
    REFERENCES `ctam`.`peptide` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`peptide_in_experiment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`peptide_in_experiment` ;

CREATE TABLE IF NOT EXISTS `ctam`.`peptide_in_experiment` (
  `peptide_id` INT NOT NULL,
  `experiment_id` INT NOT NULL,
  `phosphorylation_site` VARCHAR(255) NULL,
  `best_rt` FLOAT NULL,
  `min_ppm` DOUBLE NULL,
  `max_ppm` DOUBLE NULL,
  `mean_ppm` DOUBLE NULL,
  `min_rt` FLOAT NULL,
  `max_rt` FLOAT NULL,
  `prot_score` FLOAT NULL,
  `max_expectancy` DOUBLE NULL,
  `mean_expectancy` DOUBLE NULL,
  `max_score` FLOAT NULL,
  `mean_score` FLOAT NULL,
  `number_of_psms` INT NULL,
  `max_delta` FLOAT NULL,
  `total_ion_intensity` DOUBLE NULL,
  PRIMARY KEY (`peptide_id`, `experiment_id`),
  INDEX `experiment_peptide_in_experiment_idx` (`experiment_id` ASC),
  CONSTRAINT `peptide_peptide_in_experiment`
    FOREIGN KEY (`peptide_id`)
    REFERENCES `ctam`.`peptide` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `experiment_peptide_in_experiment`
    FOREIGN KEY (`experiment_id`)
    REFERENCES `ctam`.`experiment` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
COMMENT = 'corresponding to combiPeptData';


-- -----------------------------------------------------
-- Table `ctam`.`observed_RT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`observed_RT` ;

CREATE TABLE IF NOT EXISTS `ctam`.`observed_RT` (
  `experiment_id` INT NOT NULL,
  `run_id` INT NOT NULL,
  `peptide_id` INT NOT NULL,
  `value` FLOAT NOT NULL,
  PRIMARY KEY (`experiment_id`, `run_id`, `peptide_id`),
  INDEX `peptide_calculated_RT_idx` (`peptide_id` ASC),
  CONSTRAINT `experiment_and_run_observed_RT`
    FOREIGN KEY (`experiment_id` , `run_id`)
    REFERENCES `ctam`.`runs_in_experiment` (`experiment_id` , `run_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `peptide_observed_RT`
    FOREIGN KEY (`peptide_id`)
    REFERENCES `ctam`.`peptide` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`run_cell_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`run_cell_line` ;

CREATE TABLE IF NOT EXISTS `ctam`.`run_cell_line` (
  `run_id` INT NOT NULL,
  `cell_line_used_id` INT NOT NULL,
  PRIMARY KEY (`run_id`, `cell_line_used_id`),
  INDEX `cell_line_run_cell_line_idx` (`cell_line_used_id` ASC),
  CONSTRAINT `run_run_cell_line`
    FOREIGN KEY (`run_id`)
    REFERENCES `ctam`.`run` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cell_line_run_cell_line`
    FOREIGN KEY (`cell_line_used_id`)
    REFERENCES `ctam`.`cell_line_used` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`kinase_synonyms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`kinase_synonyms` ;

CREATE TABLE IF NOT EXISTS `ctam`.`kinase_synonyms` (
  `protein_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`, `protein_id`),
  INDEX `protein_id_kinase_synonyms_idx` (`protein_id` ASC),
  CONSTRAINT `protein_id_kinase_synonyms`
    FOREIGN KEY (`protein_id`)
    REFERENCES `ctam`.`kinase` (`protein_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ctam`.`regulator_kinase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ctam`.`regulator_kinase` ;

CREATE TABLE IF NOT EXISTS `ctam`.`regulator_kinase` (
  `regulator_id` INT NOT NULL,
  `kinase_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`regulator_id`, `kinase_id`),
  INDEX `kinase_regulator_kinase_idx` (`kinase_id` ASC),
  CONSTRAINT `regulator_regulator_kinase`
    FOREIGN KEY (`regulator_id`)
    REFERENCES `ctam`.`regulator` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `kinase_regulator_kinase`
    FOREIGN KEY (`kinase_id`)
    REFERENCES `ctam`.`kinase` (`protein_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

USE `control` ;

-- -----------------------------------------------------
-- Table `control`.`schema`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `control`.`schema` ;

CREATE TABLE IF NOT EXISTS `control`.`schema` (
  `active_schema` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`active_schema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `control`.`version`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `control`.`version` ;

CREATE TABLE IF NOT EXISTS `control`.`version` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `version` VARCHAR(45) NOT NULL,
  `date` VARCHAR(45) NOT NULL,
  `num_cell_line` INT NULL,
  `num_experiment` INT NULL,
  `num_treatment` INT NULL,
  `num_kinase` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
